[workspace]
resolver = "2"
members = ["phone-cam4linux", "crates/squigl-cli", "crates/squigl"]

[workspace.package]
version = "0.6.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/sjvrensburg/squigl"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
openh264 = "0.9"
v4l = "0.14"
ctrlc = { version = "3", features = ["termination"] }
ffmpeg-next = "9"
